/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DAY_H_RPCGEN
#define _DAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date {
	int years;
	int months;
	int days;
	int leap;
};
typedef struct date date;

#define DAYPROG1 0x20000001
#define DAYPROGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LEAP 1
extern  int * leap_1(int *, CLIENT *);
extern  int * leap_1_svc(int *, struct svc_req *);
extern int dayprog1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LEAP 1
extern  int * leap_1();
extern  int * leap_1_svc();
extern int dayprog1_1_freeresult ();
#endif /* K&R C */

#define DAYPROG2 0x20000002
#define DAYPROGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DAYS 2
extern  int * days_1(date *, CLIENT *);
extern  int * days_1_svc(date *, struct svc_req *);
extern int dayprog2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DAYS 2
extern  int * days_1();
extern  int * days_1_svc();
extern int dayprog2_1_freeresult ();
#endif /* K&R C */

#define DAYPROG3 0x20000003
#define DAYPROGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COMPUTATION 3
extern  int * computation_1(int *, CLIENT *);
extern  int * computation_1_svc(int *, struct svc_req *);
extern int dayprog3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COMPUTATION 3
extern  int * computation_1();
extern  int * computation_1_svc();
extern int dayprog3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date (XDR *, date*);

#else /* K&R C */
extern bool_t xdr_date ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DAY_H_RPCGEN */
